name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish webpages and jupyter slides
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: |
            for filename in $(ls lunchtime*/*.ipynb)
            do
                jupyter nbconvert $filename --to slides --execute || echo "nbconvert error ($filename)"
            done
      - run: mv README.md lunchtime* dist/.
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        name: Deploy to gh-pages
        with:
          branch: gh-pages
          folder: dist
          single-commit: true
